# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: maximognev/otus-lesson
  tag: "v10"
  pullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
      - path: /otusapp/(.*)
        pathType: ImplementationSpecific

  tls: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi

postgresql:
  enabled: true
  auth:
    postgresPassword: sfsdretrwsdfdsfd
    username: myuser
    password: qwerty1
    database: UsersDb
    
  primary:
    extendedConfiguration: |
      shared_preload_libraries = 'pg_stat_statements'
      pg_stat_statements.max = 10000
      pg_stat_statements.track = all
    initdb:
      user: postgres
      password: sfsdretrwsdfdsfd
      scripts:
        init.sql: |
          CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
          
  containerPorts:
    postgresql: 5432
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    customMetrics:
      pg_stat_custom:
        query: "SELECT db.datname, queryid, sum(calls) as calls, sum(total_exec_time) as total_time_seconds, sum(min_exec_time) as min_time_seconds, sum(max_exec_time) as max_time_seconds, sum(mean_exec_time) as mean_time_seconds FROM pg_stat_statements JOIN pg_database db ON (dbid=db.oid) where db.datname = 'UsersDb' group by db.datname, queryid"
        metrics:
          - datname:
              usage: "LABEL"
              description: "Database name"
          - queryid:
              usage: "LABEL"
              description: "Query ID"
          - calls:
              usage: "COUNTER"
              description: "Number of times executed"
          - total_time_seconds:
              usage: "COUNTER"
              description: "Total time spent in the statement, in seconds"
          - min_time_seconds:
              usage: "GAUGE"
              description: "Minimum time spent in the statement, in seconds"
          - max_time_seconds:
              usage: "GAUGE"
              description: "Maximum time spent in the statement, in seconds"
          - mean_time_seconds:
              usage: "GAUGE"
              description: "Mean time spent in the statement, in seconds"
      pg_stat_database:
        query: "select ut.datname, ut.numbackends, ut.tup_fetched from pg_stat_database ut where ut.datname = 'UsersDb'"
        metrics:
          - datname:
             usage: "LABEL"
             description: "Database name"
          - numbackends:
             usage: "COUNTER"
             description: "Counter"
          - tup_fetched:
             usage: "COUNTER"
             description: "Counter"
      pg_database:
        query: "SELECT d.datname AS name, CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE 0 END AS size_bytes FROM pg_catalog.pg_database d where d.datname = 'UsersDb'"
        metrics:
          - name:
              usage: "LABEL"
              description: "Name of the database"
          - size_bytes:
              usage: "GAUGE"
              description: "Size of the database in bytes"
              
metrics:
  serviceMonitor:
    enabled: true
