apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-orders-config
data:
  ORDERS_DB_NAME: {{ .Values.postgresorders.auth.database }}


---
apiVersion: v1
kind: Secret
metadata:
  name: otus-orders-secret
type: Opaque
data:
  ORDERS_DB_PASSWORD: {{ .Values.postgresorders.auth.password | b64enc | quote }}
  ORDERS_DB_USERNAME: {{ .Values.postgresorders.auth.username | b64enc | quote }}

  