apiVersion: v1
kind: Secret
metadata:
  name: otus-secret
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.jwt.secret.key| b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-kafka-server
data:
  KAFKA_BOOTSTRAP: {{ .Values.kafka.server }}
  