@startuml
skinparam defaultTextAlignment center

actor User [
    User request
]

rectangle Kubernetes #line.dotted; {
rectangle "Profile mcs" {
component Profile [
    User Service
    GET /api/profile/{userId} 
    PUT /api/profile/{userId}
]

database "UsersDb" {
}
}
rectangle "Auth mcs" {
component Auth [
  Auth Service
  POST /api/auth/create 
  POST /api/auth/login
] 
database "AuthDb" {
}
}
rectangle "Order mcs" {
component Order [
  Order Service
  GET /api/orders
  POST /api/orders 
] 
database "OrderDb" {
}
}

component Gateway [
    Api Gateway
    (Traefik)
]

}


User -right-> Gateway
Gateway -down-> Profile
Gateway -down-> Auth: GET Authorization: Bearer Token
Gateway -down-> Order: GET Получение списка заказов с токеном идемпотентности 
Auth .down.> AuthDb
Profile .down.> UsersDb
Order .down.> OrderDb

@enduml