@startuml
actor "Клиент" as client
autonumber "<font color=red><b>(0)"
box "Процесс оформления заказа"
participant "Сервис заказов" as order
participant "Сервис биллинга" as billing
participant "Брокер сообщений" as broker
participant "Сервис оповещений" as notification
end box

activate broker
client -> order++: Создание заказа
order -> broker: Отправка "Создание заказа"
billing <- broker: Получение "Создание заказа"
activate billing
billing -> broker:  Событие "Заказ оплачен"
billing -> broker:  Событие "Notification"
deactivate billing
order <- broker : "Заказ оплачен" 
order --> client--:  Статус заказа
broker -> notification++: Cобытие Notification
notification -> notification:  Отправка уведомления (Email, SMS, Push)
notification --> broker--: Отчет об отправке
deactivate broker
@enduml