{
 "title": "Otus User Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Service API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (method) (rate(http_requests_received_total[1m])) ",
       "legendFormat": "RPS {{method}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (method) (rate(http_request_duration_seconds_count{code=\"500\"}[1m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency 0.5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, \r\n      sum by (le, method) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000\r\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency 0.95",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n      sum by (le, method) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency 0.99",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \r\n      sum by (le, method) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, \r\n      sum by (le, method) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests[1m])) ",
       "legendFormat": "RPS {{action}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_service) (rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m]))",
       "legendFormat": "Erros"
      }
     ]
    },
    {
     "title": "Latency 0.5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, \r\n      sum by (le, method) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000\r\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency 0.95",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n      sum by (le, method) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency 0.99",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \r\n      sum by (le, method) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Latency max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, \r\n      sum by (le, method) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "POD CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\",pod=~\"otus-demo-.*\"}[1m])) * 100)",
       "legendFormat": "CPU core {{cpu}} loading [%]"
      }
     ]
    },
    {
     "title": "POD Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{pod=~\"otus-demo.*\"}",
       "legendFormat": "POD {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{name=\"UsersDb\"}",
     "legendFormat": "1 MiB"
    }
   ]
  },
  {
   "title": "DB Query Count (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_stat_custom_calls{datname=\"UsersDb\"}[1m]))",
     "legendFormat": "2"
    }
   ]
  },
  {
   "title": "Execution Mean time (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_custom_mean_time_seconds[1m]))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"UsersDb\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=\"UsersDb\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=\"myapp\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=\"myapp\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=\"myapp\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=\"myapp\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}