apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-lesson-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-lesson
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: otus-lesson
    spec:
      containers:
      - name: otus-lesson
        image: maximognev/otus-lesson:docker
        resources:
          limits:
            memory: 258Mi
            cpu: 100m
        ports:
          - name: web
            containerPort: 8000
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          httpGet:
            path: /health
            port: 8000
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 15
          httpGet:
            path: /health
            port: 8000
          

        