apiVersion: v1
kind: Pod
metadata:
  name: otus-lesson-pod
  labels:
    name: otus-lesson
spec:
  containers:
  - name: otus-lesson
    image: maximognev/otus-lesson:docker
    resources:
      limits:
        memory: 258Mi
        cpu: 100m
    ports:
      - containerPort: 80
