apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-auth-config
data:
  AUTH_DB_NAME: {{ .Values.postgresauth.auth.database }}


---
apiVersion: v1
kind: Secret
metadata:
  name: otus-auth-secret
type: Opaque
data:
  AUTH_DB_PASSWORD: {{ .Values.postgresauth.auth.password | b64enc | quote }}
  AUTH_DB_USERNAME: {{ .Values.postgresauth.auth.username | b64enc | quote }}

  